# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "main"
      - "refs/tags/*"

pr:
  branches:
    include:
      - "main"
  paths:
    include:
      - ".azure/gpu-tests.yml"
      - "tests/**"
      - "pyproject.toml"  # includes pytest config
      - "requirements.txt"
      - "tests/requirements.txt"
      - "src/**"

jobs:
  - job: testing
    # how long to run the job before automatically cancelling
    timeoutInMinutes: "30"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"
    strategy:
      matrix:
        'Lightning pkg':
          #image: "pytorchlightning/pytorch_lightning:base-cuda-py3.10-torch1.13-cuda11.7.1"
          image: "nvidia/cuda:11.6.2-devel-ubuntu20.04"
          PYTHON_VERSION: '3.9'
          PYTORCH_VERSION: '1.13'
          CUDA_VERSION_MM: '116'
    pool: 'lit-rtx-3090'
    variables:
      DEVICES: $( python -c 'print("$(Agent.Name)".split("_")[-1])' )
      FREEZE_REQUIREMENTS: "1"
      # HOROVOD_CUDA_HOME: $(CUDA_TOOLKIT_ROOT_DIR)
      HOROVOD_GPU_OPERATIONS: NCCL
      HOROVOD_WITH_PYTORCH: 1
      HOROVOD_WITHOUT_TENSORFLOW: 1
      HOROVOD_WITHOUT_MXNET: 1
      HOROVOD_WITH_GLOO: 1
      HOROVOD_WITH_MPI: 1
      PL_USE_MOCKED_MNIST: 1
    container:
      image: $(image)
      # default shm size is 64m. Increase it to avoid:
      # 'Error while creating shared memory: unhandled system error, NCCL version 2.7.8'
      options: "--gpus=all --shm-size=6gb -v /usr/bin/docker:/tmp/docker:ro"
    workspace:
      clean: all
    steps:

    - script: |
        container_id=$(head -1 /proc/self/cgroup|cut -d/ -f3)
        echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
        /tmp/docker exec -t -u 0 $container_id \
          sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
        echo "##vso[task.setvariable variable=CONTAINER_ID]$container_id"
      displayName: 'Install Sudo in container (thanks Microsoft!)'

    - bash: |
        add-apt-repository ppa:deadsnakes/ppa
        apt-get -y update -qq --fix-missing
        apt-get -y install \
          build-essential \
          python$PYTHON_VERSION \
          python$PYTHON_VERSION-dev \
          python3-distutils \
          python3-pip \
          pciutils \
          curl
        update-alternatives --install /usr/bin/python python /usr/bin/python$PYTHON_VERSION 1
        update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
      displayName: 'Install sys & python'  # CUDA image if completely blind

    - bash: |
        echo "##vso[task.setvariable variable=CUDA_VISIBLE_DEVICES]$(DEVICES)"
        echo "##vso[task.setvariable variable=TORCH_URL]https://download.pytorch.org/whl/cu${CUDA_VERSION_MM}/torch_stable.html"
      displayName: 'set env. vars'

    - bash: |
        echo $CUDA_VISIBLE_DEVICES
        echo $TORCH_URL
        lspci | egrep 'VGA|3D'
        whereis nvidia
        nvidia-smi
        which python && which pip
        python --version
        pip --version
        pip list
      displayName: 'Image info & NVIDIA'

    - bash: |
        apt-get update --fx-missing
        apt-get install -y libopenmpi-dev openmpi-bin
        pip install "torch==${PYTORCH_VERSION}" -f ${TORCH_URL}
        find / -iname 'Python.h'
        pip install -e . -r tests/requirements.txt
      displayName: 'Install package & extras'

    - bash: |
        HOROVOD_BUILT=$(python -c "import horovod.torch; horovod.torch.nccl_built(); print('SUCCESS')" || true)
        if [[ $HOROVOD_BUILT != "SUCCESS" ]]; then
          pip uninstall -y horovod
          grep "horovod" requirements.txt > requires-horovod.txt
          pip install --no-cache-dir -r requires-horovod.txt
        fi
        horovodrun --check-build
        python -c "import horovod.torch"
        pip list | grep -e torch -e horovod
      displayName: 'Reinstall Horovod (if necessary)'

    - bash: |
        pip list
        python -c "import torch ; mgpu = torch.cuda.device_count() ; assert mgpu == 2, f'GPU: {mgpu}'"
      displayName: 'Env details'

    - bash: pytest src/ tests/ --cov=lightning_horovod -v
      displayName: 'Testing: standard'
      timeoutInMinutes: "20"

    - bash: |
        python -m coverage report
        python -m coverage xml
        python -m codecov --token=$(CODECOV_TOKEN) --commit=$(Build.SourceVersion) \
          --flags=gpu,pytest --name="GPU-coverage" --env=linux,azure
        ls -l
      displayName: 'Statistics'
